services:
  nginx:
    image: nginx:alpine
    ports: 
      - "80:80"
    volumes:
      - ./portfolio/backend/public:/var/www/backend/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - backend
    container_name: gladkix_nginx_dev
    networks:
      - gladkix_network

  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./portfolio/backend:/var/www/backend
      - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
    restart: always
    container_name: gladkix_backend_dev
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://gladkix:1234@db:3306/gladkix?serverVersion=8.0&charset=utf8mb4"
      APP_ENV: "${APP_ENV:-prod}"
      APP_DEBUG: "${APP_DEBUG:-0}"
    networks:
      - gladkix_network

  db:
    image: mysql:8.4
    restart: always
    volumes:
      - db_data:/var/lib/mysql
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gladkix
      MYSQL_USER: gladkix
      MYSQL_PASSWORD: 1234
    container_name: gladkix_db_dev
    networks:
      - gladkix_network

volumes:
  db_data:

networks:
  gladkix_network:
    driver: bridge
