parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'


    # Кастомные репозитории
    App\Article\Repository\ArticleRepository:
        tags: ['doctrine.repository_service']
        
    App\Category\Repository\CategoryRepository:
        tags: ['doctrine.repository_service']
        
    App\Project\Repository\ProjectRepository:
        tags: ['doctrine.repository_service']
        
    App\Tag\Repository\TagRepository:
        tags: ['doctrine.repository_service']
